name: torch_gpu
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ipykernel=6.2.0
  - ipython=7.27.0
  - ipywidgets=7.6.3
  - matplotlib=3.4.2
  - opencv=3.4.2
  - pandas=1.3.2
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.0.1
  - python=3.7.11
  - python-dateutil=2.8.2
  - pytorch=1.9.1=py3.7_cuda10.2_cudnn7_0
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - torchaudio=0.9.1
  - torchvision=0.10.1
  - pip:
    - gymnasium=0.27.1
    - tqdm=4.38.0